Repository snippet-labs/LAB, pull requests merged in 2025-08, with the labels that each got.

#10 [CLIENT] [SECTION] Know-us section
  src/components/general/Button/Button.tsx
  src/components/general/Capsule/Capsule.tsx
  src/components/general/Cards/Cards.tsx
  src/components/general/Cards/Cards.types.ts
  src/components/general/Footer.tsx
  src/components/general/Navbar.tsx
  src/components/section/Header/Header.tsx
  src/components/section/Knowus/Knowus.tsx
Labels: client, component, section

#17 [FEATURE] [CLIENT] Footer of the application
  src/app/layout.tsx
  src/components/general/Footer.tsx
  src/components/general/Marqee/Marqee.tsx
  src/components/general/Tooltip/Tooltip.tsx
  src/components/section/Technology/Technology.tsx
  src/components/ui/animated-tooltip.tsx
  src/data/siteMap.ts
  src/data/teamDetails.ts
Labels: client, component, ui

#21 [FLAG] [CLIENT] Newsletter subscription
  src/components/general/Footer.tsx
  src/components/general/Tooltip/Tooltip.tsx
  src/hooks/useFeatureFlag.ts
Labels: client, component, optimise

#22 [CLIENT] [PAGE] Products Page
  src/app/layout.tsx
  src/app/products/page.tsx
  src/components/general/Footer.tsx
  src/components/general/GyroCard/GyroCard.tsx
  src/components/general/GyroCard/GyroCard.types.ts
  src/components/ui/3d-card.tsx
  src/data/productDetails.ts
  src/hooks/useFeatureFlag.ts
  src/hooks/useSectionInView.ts
Labels: client, ui

#24 [CLIENT] [GENERAL] Underdevelopment component
  src/app/products/page.tsx
  src/components/general/Footer.tsx
  src/components/general/UnderDevelopment/UnderDevelopment.tsx
  src/components/ui/3d-card.tsx
  src/components/ui/animated-tooltip.tsx
  src/components/ui/background-beams.tsx
  src/components/ui/container-text-flip.tsx
  src/components/ui/floating-navbar.tsx
Labels: client, component, ui, optimise

#25 [CLIENT] [PAGE] Team page
  public/images/akash.png
  public/images/hemangshu.png
  public/images/subhajit.png
  public/images/susanta.png
  public/images/suvajit.png
  public/images/tushit.png
  src/app/products/page.tsx
  src/components/general/Footer.tsx
  src/components/general/GyroCard/GyroCard.tsx
  src/components/general/GyroCard/GyroCard.types.ts
  src/components/ui/3d-card.tsx
  src/data/aboutTeam.ts
  src/data/productDetails.ts
  src/data/teamDetails.ts
  src/hooks/useFeatureFlag.ts
  src/hooks/useSectionInView.ts
Labels: client, component

#26 [CLIENT] [PAGE] Team page
  public/avatar/akash.png
  public/avatar/hemangshu.png
  public/avatar/subhajit.png
  public/avatar/subham.png
  public/avatar/susanta.png
  public/avatar/suvajit.png
  public/avatar/tushit.png
  public/fonts/Cursive.ttf
  public/images/akash.png
  public/images/hemangshu.png
  public/images/subhajit.png
  public/images/susanta.png
  public/images/suvajit.png
  public/images/tushit.png
  src/app/layout.tsx
  src/app/page.tsx
  src/app/team/page.tsx
  src/components/general/TracingCard/TracingCard.tsx
  src/components/ui/tracing-beam.tsx
  src/data/aboutTeam.ts
  src/data/teamDetails.ts
  src/helpers/font.ts
Labels: client, component

#28 [CLIENT] [LAYOUT] Footer links redirection to underdevelopment
  src/app/about/page.tsx
  src/app/blog/page.tsx
  src/app/help/page.tsx
  src/app/releases/page.tsx
  src/app/status/page.tsx
  src/app/terms/page.tsx
  src/components/general/Footer.tsx
  src/data/siteMap.ts
  src/hooks/useFeatureFlag.ts
Labels: client, component, optimise
